name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Run Python script for text replacements
    #   run: python3 replace_text.py
    # commented out for the stable version

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      continue-on-error: true
      with:
        server: ftp.datacode.online
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./ 
        protocol: ftp
        method: sync
        # dangerous-clean-slate: true
        server-dir: /